Feat/prio algo2
remunds/data-offloading-box pull request #27
Opened 2021-01-29 18:26 UTC by remunds

2021-02-03 12:28 UTC, iBims1JFK requested changes
- [ ] Großzügige Dokumentation innerhalb des Codes durch aussagekräftige Kommentare.

- [ ] Sinnvolle und eindeutige Namensgebung der Variablen, Methoden und Komponenten

- [x] Sinnvolle Wahl der verwendeten Datenstrukturen
- [x] Modularität gegeben
- [x] Keine Redundanz
- [x] Code erfüllt seine Intention
- [x] node standard eingehalten

2021-02-03 12:28 UTC, iBims1JFK commented on app.js
>    if (fileToSend === -1) {
Anstatt es auf -1 zu setzten, könne man auch auf null checken

2021-02-03 12:28 UTC, iBims1JFK commented on app.js
> -    res.status(400)
Ich glaube hier müsste trotzdem ein 200 Status Code geworfen werden, da die Anfrage richtig war. Wenn es kein Element dazu gibt, ist Respone einfach leer. 400 sollte geworfen werden, wenn in der Query etwas steht, was nicht old oder new ist. Dann wurde eine "Bad request" gestellt.

2021-02-03 12:28 UTC, iBims1JFK commented on app.js
>    if (fileToSend === -1) {
Eigt ist ein check hier insgesamt unnötig und du könntest den Body der if Abfrage ab 139 in die den else Body ab 135 packen. Dann sparst du dir den check of -1 oder null.

2021-02-04 18:26 UTC, laura-jehn approved these changes
approved requested changes and rebase

2021-02-04 18:27 UTC, merged